// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: tprotos/tprotos.proto

package tprotos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TProtoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TProtoRequest) Reset() {
	*x = TProtoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tprotos_tprotos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TProtoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TProtoRequest) ProtoMessage() {}

func (x *TProtoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tprotos_tprotos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TProtoRequest.ProtoReflect.Descriptor instead.
func (*TProtoRequest) Descriptor() ([]byte, []int) {
	return file_tprotos_tprotos_proto_rawDescGZIP(), []int{0}
}

func (x *TProtoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TProtoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *TProtoResponse) Reset() {
	*x = TProtoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tprotos_tprotos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TProtoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TProtoResponse) ProtoMessage() {}

func (x *TProtoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tprotos_tprotos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TProtoResponse.ProtoReflect.Descriptor instead.
func (*TProtoResponse) Descriptor() ([]byte, []int) {
	return file_tprotos_tprotos_proto_rawDescGZIP(), []int{1}
}

func (x *TProtoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_tprotos_tprotos_proto protoreflect.FileDescriptor

var file_tprotos_tprotos_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x22, 0x23, 0x0a, 0x0d, 0x54, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x24, 0x0a, 0x0e, 0x54, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x4e, 0x0a, 0x0e, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3c, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x54, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x2e, 0x74, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x54, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x54, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e,
	0x2f, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tprotos_tprotos_proto_rawDescOnce sync.Once
	file_tprotos_tprotos_proto_rawDescData = file_tprotos_tprotos_proto_rawDesc
)

func file_tprotos_tprotos_proto_rawDescGZIP() []byte {
	file_tprotos_tprotos_proto_rawDescOnce.Do(func() {
		file_tprotos_tprotos_proto_rawDescData = protoimpl.X.CompressGZIP(file_tprotos_tprotos_proto_rawDescData)
	})
	return file_tprotos_tprotos_proto_rawDescData
}

var file_tprotos_tprotos_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_tprotos_tprotos_proto_goTypes = []interface{}{
	(*TProtoRequest)(nil),  // 0: tprotos.TProtoRequest
	(*TProtoResponse)(nil), // 1: tprotos.TProtoResponse
}
var file_tprotos_tprotos_proto_depIdxs = []int32{
	0, // 0: tprotos.DetailsService.GetTProto:input_type -> tprotos.TProtoRequest
	1, // 1: tprotos.DetailsService.GetTProto:output_type -> tprotos.TProtoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tprotos_tprotos_proto_init() }
func file_tprotos_tprotos_proto_init() {
	if File_tprotos_tprotos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tprotos_tprotos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TProtoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tprotos_tprotos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TProtoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tprotos_tprotos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tprotos_tprotos_proto_goTypes,
		DependencyIndexes: file_tprotos_tprotos_proto_depIdxs,
		MessageInfos:      file_tprotos_tprotos_proto_msgTypes,
	}.Build()
	File_tprotos_tprotos_proto = out.File
	file_tprotos_tprotos_proto_rawDesc = nil
	file_tprotos_tprotos_proto_goTypes = nil
	file_tprotos_tprotos_proto_depIdxs = nil
}
